### ISSUE TITLE
Getting "ResponseObservation is null! The application will terminate." when running on .NET Core

### ISSUE THREAD

**Issue by carlos-sarmiento** [NikEyX/SC2-CSharpe-Starterkit#1]
I'm trying to understand what is happening that might be triggering this error. I migrated the code (on windows) from .NET Framework to .NET core (v2.1). I made no changes to the code.

This is the full project file I'm using: 

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Google.Protobuf" Version="3.5.1" />
  </ItemGroup>

</Project>
```

**Comment by NikEyX** [comment]
Does it work with standard .net? I'm not very familiar with Core. It also looks like you're using your own protobuf version based on NuGet? Use the dll that's provided, which ensures that the proto buffs will be readable, as Google Protobufs have a habit of breaking old behaviour
